apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: test
  labels:
    app: grpc-server
spec:
  selector:
    app: grpc-server
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP